### ISSUE TITLE
Crew Rotation Contract completes with any vessel landing

### ISSUE THREAD

**Issue by mwerle** [severedsolo/KerbinSpaceStation#43]
Accepted a Crew Rotation Contract (fitted in nicely with a Tourism one), launched the new Crew to the Station, and docked.
I then landed an unkerballed launch stage (from another mission), and the contract completed.

2 issues:
1. The station was empty at the time the contract was generated; Crew Rotation should only be offered if the station has a crew.
2. The contract should only be completed when (some of) the Crew  on the Station is returned to Kerbin.

**Comment by severedsolo** [comment]
Agreed - known issue, I'm surprised it's not come up sooner to be honest. As soon as I fix my KSP machine (tomorrow I hope) I'll put some additional logic in there.

The fix for this will be twofold:

1) introduce a new "Crew the station" contract. This will appear when the station is unmanned (but not within a few days of an evacuate mission, in case you are sending the crew back).

2) Crew Rotation missions will require the entire current crew to be recovered, as well as adding a new crew to the station. (as per #40)

**Comment by severedsolo** [comment]
Fixed
